#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]
then
  rm -f /etc/freeradius/3.0/sites-enabled/vlan || true
  rm -f /etc/freeradius/3.0/sites-enabled/vlan_inner-tunnel || true
  rm -f /etc/freeradius/3.0/mods-enabled/ldap_vlan || true
  rm -f /etc/freeradius/3.0/mods-enabled/perl_vlan || true
  systemctl try-restart freeradius.service || true
fi

#DEBHELPER#
