CREATE TABLE radius_vlan (
	ID		SERIAL		PRIMARY KEY,
	Description	TEXT		NOT NULL,
	VLAN_ID		INT		NOT NULL CHECK (VLAN_ID BETWEEN 1 AND 4095),
	PRIORITY	INT		NOT NULL UNIQUE DEFAULT 0
);

CREATE TABLE radius_vlan_group (
	VLAN_ID		INT		NOT NULL REFERENCES radius_vlan(ID)
						ON UPDATE CASCADE
						ON DELETE CASCADE,
	Group		TEXT		NOT NULL REFERENCES groups(Act)
						ON UPDATE CASCADE
						ON DELETE CASCADE
);

CREATE TABLE radius_vlan_role (
	VLAN_ID		INT		NOT NULL REFERENCES radius_vlan(ID)
						ON UPDATE CASCADE
						ON DELETE CASCADE,
	Role		TEXT		NOT NULL REFERENCES security_roles(Role)
						ON UPDATE CASCADE
						ON DELETE CASCADE
);
